const reporting_info = [
    {
      "id": 1,
      "name": "Search page mockup",
      "developers": ["Robert Fox", "Kent Peacock", "Robert Fox", "Kent Peacock", "Kent Peacock", "Kent Peacock"],
      "workType": ["Programming", "Meetings", "Programming", "Meetings"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 237.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 2,
      "name": "Two levels of the menu mockup",
      "developers": ["Robert Fox"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 1567.60,
      "myTime": 15.00,
      "efficiency": null
    },
    {
      "id": 3,
      "name": "Edit pictures",
      "developers": ["Dianne Russel", "Adam Gordon", "Dianne Russel", "Adam Gordon"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 678.20,
      "myTime": 67.00,
      "efficiency": null
    },
    {
      "id": 4,
      "name": "Subdomain home pages mockup",
      "developers": ["Dianne Russel"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 756.70,
      "myTime": 75.00,
      "efficiency": null
    },
    {
      "id": 5,
      "name": "Landing page mockup",
      "developers": ["Dianne Russel"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 345.60,
      "myTime": 45.00,
      "efficiency": null
    },
    {
      "id": 6,
      "name": "Search page mockup",
      "developers": ["Robert Fox", "Kent Peacock", "Sheldon Cooper", "Vasya Pupkin"],
      "workType": ["Programming", "Meetings", "Graphic Design", "Markup"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 237.17,
      "myTime": 23.00,
      "efficiency": 100 
    },
    {
      "id": 7,
      "name": "Search page mockup 7",
      "developers": ["Courtney Henry", "Kent Peacock", "Courtney Henry", "Kent Peacock"],
      "workType": ["Programming", "Meetings", "Programming", "Meetings"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 232.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 8,
      "name": "Landing page mockup",
      "developers": ["Courtney Henry", "Augusta Walter"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 345.60,
      "myTime": 45.00,
      "efficiency": null
    },
    {
      "id": 9,
      "name": "Search page mockup",
      "developers": ["Courtney Henry", "Kent Peacock"],
      "workType": ["Programming", "Meetings"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 232.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 10,
      "name": "Search page mockup",
      "developers": ["Robert Fox", "Kent Peacock", "Nick Johnson", "Ralph Edward", "Kate Middleton", "Dianne Russel"],
      "workType": ["Programming", "Meetings", "Graphic Design", "Markup"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 232.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 11,
      "name": "Search page mockup",
      "developers": ["Robert Fox", "Kent Peacock", "Robert Fox", "Kent Peacock", "Kent Peacock", "Kent Peacock"],
      "workType": ["Programming", "Meetings", "Programming", "Meetings"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 237.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 12,
      "name": "Two levels of the menu mockup",
      "developers": ["Robert Fox"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 1567.60,
      "myTime": 15.00,
      "efficiency": null
    },
    {
      "id": 13,
      "name": "Edit pictures",
      "developers": ["Dianne Russel", "Adam Gordon", "Dianne Russel", "Adam Gordon"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 678.20,
      "myTime": 67.00,
      "efficiency": null
    },
    {
      "id": 14,
      "name": "Subdomain home pages mockup",
      "developers": ["Dianne Russel"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 756.70,
      "myTime": 75.00,
      "efficiency": null
    },
    {
      "id": 15,
      "name": "Landing page mockup",
      "developers": ["Dianne Russel"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 345.60,
      "myTime": 45.00,
      "efficiency": null
    },
    {
      "id": 16,
      "name": "Search page mockup",
      "developers": ["Robert Fox", "Kent Peacock", "Sheldon Cooper", "Vasya Pupkin"],
      "workType": ["Programming", "Meetings", "Graphic Design", "Markup"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 237.17,
      "myTime": 23.00,
      "efficiency": 100 
    },
    {
      "id": 17,
      "name": "Search page mockup 7",
      "developers": ["Courtney Henry", "Kent Peacock", "Courtney Henry", "Kent Peacock"],
      "workType": ["Programming", "Meetings", "Programming", "Meetings"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 232.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 18,
      "name": "Landing page mockup",
      "developers": ["Courtney Henry", "Augusta Walter"],
      "workType": ["Graphic Design"],
      "status": false,
      "estimation": 0.0,
      "totalTime": 345.60,
      "myTime": 45.00,
      "efficiency": null
    },
    {
      "id": 19,
      "name": "Search page mockup",
      "developers": ["Courtney Henry", "Kent Peacock"],
      "workType": ["Programming", "Meetings"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 232.17,
      "myTime": 23.00,
      "efficiency": 100
    },
    {
      "id": 20,
      "name": "Search page mockup",
      "developers": ["Robert Fox", "Kent Peacock", "Nick Johnson", "Ralph Edward", "Kate Middleton", "Dianne Russel"],
      "workType": ["Programming", "Meetings", "Graphic Design", "Markup"],
      "status": true,
      "estimation": 0.0,
      "totalTime": 232.17,
      "myTime": 23.00,
      "efficiency": 100
    }
  ]
